// lib/invite.dart

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';

// This line points to the file generated by the flutter_gen_l10n tool.
import 'package:cortex/l10n/app_localizations.dart';

/// This service manages the creation and sharing of user-specific referral links,
/// fully supporting localization.
class InviteService {

  Future<void> createAndShareReferralLink(BuildContext context) async {
    final user = FirebaseAuth.instance.currentUser;

    if (user == null) {
      debugPrint('[InviteService] Error: User not logged in.');
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('You must be logged in to share invites.')),
      );
      return;
    }

    const String androidPackageName = 'com.vertex.cortex';
    const String iosAppStoreLink = 'https://apps.apple.com/app/id6755621587';

    final String referrerId = user.uid;
    final String encodedReferrer = Uri.encodeComponent('ref=$referrerId');

    // Platform-specific store link
    late final String finalLink;

    if (Theme.of(context).platform == TargetPlatform.iOS) {
      // iOS → Direct App Store link (no referrer parameter supported)
      finalLink = iosAppStoreLink;
    } else {
      // Android → Play Store link with referrer
      finalLink =
      'https://play.google.com/store/apps/details?id=$androidPackageName&referrer=$encodedReferrer';
    }

    debugPrint('Generated store link: $finalLink');

    // Localization
    final localizations = AppLocalizations.of(context)!;
    final String shareText = localizations.inviteShareMessage(finalLink);
    final String shareSubject = localizations.inviteShareSubject;

    // Share
    await SharePlus.instance.share(
      ShareParams(
        text: shareText,
        subject: shareSubject,
      ),
    );
  }
}