// lib/invite.dart

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';

// This line points to the file generated by the flutter_gen_l10n tool.
import 'package:cortex/l10n/app_localizations.dart';

/// This service manages the creation and sharing of user-specific referral links,
/// fully supporting localization.
class InviteService {

  /// Creates a special Play Store link with a referrer and shares it
  /// via the native device share sheet.
  Future<void> createAndShareReferralLink(BuildContext context) async {
    final user = FirebaseAuth.instance.currentUser;

    // The user must be logged in to create a referral link.
    if (user == null) {
      debugPrint('[InviteService] Error: User is not logged in. Cannot create a referral link.');
      // It's good practice to show an error message to the user.
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('You must be logged in to share invites.')),
      );
      return;
    }

    // IMPORTANT: Replace this with your own app's package name!
    // This must match the 'package' attribute in your AndroidManifest.xml.
    const String packageName = 'com.vertex.cortex';

    // We use the user's unique ID (uid) as the referrer.
    final String referrerId = user.uid;

    // The parameter we will send to the Play Store: 'ref=USER_ID'.
    // It is VERY IMPORTANT to encode this to make it URL-safe.
    final String encodedReferrer = Uri.encodeComponent('ref=$referrerId');

    // This is our user-specific, "magic" Play Store link.
    final String playStoreLink = 'https://play.google.com/store/apps/details?id=$packageName&referrer=$encodedReferrer';

    debugPrint('Generated Play Store link with referrer: $playStoreLink');

    // ================== LOCALIZATION LOGIC STARTS HERE ==================

    // 1. Get the current localization instance from the context.
    // This will fetch the strings for the currently active device language.
    final localizations = AppLocalizations.of(context)!;

    // 2. Build the localized message by filling in the placeholder.
    // The text is no longer hard-coded; it comes dynamically from the .arb file.
    // The `inviteShareMessage` method expects the {playStoreLink} placeholder.
    final String shareText = localizations.inviteShareMessage(playStoreLink);

    // 3. (Optional but recommended) Localize the share subject as well.
    final String shareSubject = localizations.inviteShareSubject;

    // ====================================================================

    // Open the native share sheet with our dynamically generated content.
    await SharePlus.instance.share(
      ShareParams(
        text: shareText,
        subject: shareSubject,
      ),
    );
  }
}