// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaNXY_dmb7cV9iFWffX-2B6e13Tbichx0',
    appId: '1:561391430514:web:bb7e4f1ca60d5e4bb10beb',
    // Dummy Web ID based on Android
    messagingSenderId: '561391430514',
    projectId: 'vertex-ai-1618',
    authDomain: 'vertex-ai-1618.firebaseapp.com',
    storageBucket: 'vertex-ai-1618.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaNXY_dmb7cV9iFWffX-2B6e13Tbichx0',
    appId: '1:561391430514:android:0de290ae306149efb10beb',
    messagingSenderId: '561391430514',
    projectId: 'vertex-ai-1618',
    storageBucket: 'vertex-ai-1618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaNXY_dmb7cV9iFWffX-2B6e13Tbichx0',
    appId: '1:561391430514:ios:bb7e4f1ca60d5e4bb10beb',
    // Dummy iOS ID based on Android
    messagingSenderId: '561391430514',
    projectId: 'vertex-ai-1618',
    storageBucket: 'vertex-ai-1618.firebasestorage.app',
    iosBundleId: 'com.vertex.cortex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaNXY_dmb7cV9iFWffX-2B6e13Tbichx0',
    appId: '1:561391430514:ios:bb7e4f1ca60d5e4bb10beb',
    // Dummy macOS ID based on Android
    messagingSenderId: '561391430514',
    projectId: 'vertex-ai-1618',
    storageBucket: 'vertex-ai-1618.firebasestorage.app',
    iosBundleId: 'com.vertex.cortex',
  );
}
