// lib/chat/messages/messages.dart

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';

/// Enum to track which type of media is currently being generated by a Fal model.
/// Used to display the appropriate shimmer placeholder in the UI.
enum MediaGenerationType { none, audio, image, video }

class Message {
  /// A unique identifier for the message.
  final String? id;

  /// You know
  final String text;

  /// Returns the text completely stripped of any memory tags or their streaming fragments
  /// so that UI elements (like typing animations or raw text selection screens) never show them.
  String get displayableText {
    return text
        .replaceAll(
        RegExp(r'\s*<m(?:e(?:m(?:o(?:r(?:y(?:>[\s\S]*)?)?)?)?)?)?$',
            caseSensitive: false),
        '')
        .replaceAll(
        RegExp(r'\s*<memory>[\s\S]*?(?:</memory>|$)\s*',
            caseSensitive: false),
        '');
  }

  /// The boolean variable for controlling the message type
  final bool isUserMessage;

  /// A list of file paths for attached media (Images, PDFs, Docs, etc.).
  /// Replaces the legacy `photoPath` to support multi-modal attachments.
  final List<String> attachmentPaths;

  /// The model ID used to generate this message (if it's an AI message).
  final String? model;

  /// Indicates if this message should be included in the context for future API calls.
  final bool includeInContext;

  /// True if the user has reported this message.
  final bool isReported;

  /// Indicates that an AI response is currently being generated.
  final bool isThinking;

  /// Indicates that this message represents an error.
  final bool isError;

  /// A UI-specific property for fade animations. Defaults to 1.0.
  final double opacity;

  /// Indicates if attachments are currently being processed/uploaded.
  final bool isAttachmentUploading;

  /// Pre-parsed text spans for rich text rendering in the UI.
  final List<InlineSpan>? parsedSpans;

  /// A UI-specific notifier to efficiently update only the text of this message.
  final ValueNotifier<String> notifier;

  /// Indicates if the message should be visible in the UI.
  final bool isVisible;

  /// Indicates if web search is currently active for this message.
  final bool isWebSearchActive;

  /// Stores the citations/sources from the web search.
  final List<dynamic>? webSearchSources;

  /// Indicates the type of media currently being generated (shimmer placeholder).
  /// When set to anything other than [MediaGenerationType.none], the UI shows
  /// a shimmer placeholder appropriate for the media type.
  final MediaGenerationType pendingMediaType;

  /// Indicates if this message was generated by the dynamic chat fallback on the server.
  final bool isServerFallback;
  final DateTime? timestamp;

  Message({
    this.id,
    required this.text,
    required this.isUserMessage,
    this.attachmentPaths = const [],
    this.model,
    this.includeInContext = true,
    this.isReported = false,
    this.isThinking = false,
    this.isError = false,
    this.opacity = 1.0,
    this.isAttachmentUploading = false,
    this.parsedSpans,
    this.isVisible = true,
    this.isWebSearchActive = false,
    this.webSearchSources,
    this.pendingMediaType = MediaGenerationType.none,
    this.isServerFallback = false,
    this.timestamp,


  }) : notifier = ValueNotifier(text);

  /// Private constructor used by `copyWith` and `fromMap`.
  Message._private({
    required this.id,
    required this.text,
    required this.isUserMessage,
    required this.attachmentPaths,
    required this.model,
    required this.includeInContext,
    required this.isReported,
    required this.isThinking,
    required this.isError,
    required this.opacity,
    required this.isAttachmentUploading,
    required this.parsedSpans,
    required this.notifier,
    required this.isVisible,
    required this.isWebSearchActive,
    required this.webSearchSources,
    required this.pendingMediaType,
    required this.isServerFallback,
    this.timestamp,
  });

  /// Helper getter to check if the message has any attachments.
  bool get hasAttachments => attachmentPaths.isNotEmpty;

  /// Creates a brand new user message, automatically generating a UUID.
  static Message user({
    required String text,
    List<String> attachmentPaths = const [],
    String? model,
  }) {
    return Message(
      id: const Uuid().v4(),
      text: text,
      isUserMessage: true,
      attachmentPaths: attachmentPaths,
      model: model,
      timestamp: DateTime.now(),
    );
  }

  Message copyWith({
    String? id,
    bool forceNewId = false,
    String? text,
    bool? isUserMessage,
    List<String>? attachmentPaths,
    String? model,
    bool? includeInContext,
    bool? isReported,
    bool? isThinking,
    bool? isError,
    double? opacity,
    bool? isAttachmentUploading,
    List<InlineSpan>? parsedSpans,
    bool? isVisible,
    bool? isWebSearchActive,
    List<dynamic>? webSearchSources,
    MediaGenerationType? pendingMediaType,
    bool? isServerFallback,
    DateTime? timestamp,
  }) {
    // Reuse existing notifier if text hasn't changed to save resources.
    final newNotifier =
    (text != null && text != this.text) ? ValueNotifier(text) : notifier;

    if (text != null) {
      newNotifier.value = text;
    }

    final String? finalId = forceNewId ? const Uuid().v4() : (id ?? this.id);

    return Message._private(
      id: finalId,
      text: text ?? this.text,
      isUserMessage: isUserMessage ?? this.isUserMessage,
      // List.from creates a copy of the list to ensure immutability
      attachmentPaths: attachmentPaths != null
          ? List.from(attachmentPaths)
          : this.attachmentPaths,
      model: model ?? this.model,
      includeInContext: includeInContext ?? this.includeInContext,
      isReported: isReported ?? this.isReported,
      isThinking: isThinking ?? this.isThinking,
      isError: isError ?? this.isError,
      opacity: opacity ?? this.opacity,
      isAttachmentUploading:
      isAttachmentUploading ?? this.isAttachmentUploading,
      parsedSpans: parsedSpans ?? this.parsedSpans,
      notifier: newNotifier,
      isVisible: isVisible ?? this.isVisible,
      isWebSearchActive: isWebSearchActive ?? this.isWebSearchActive,
      webSearchSources: webSearchSources ?? this.webSearchSources,
      pendingMediaType: pendingMediaType ?? this.pendingMediaType,
      isServerFallback: isServerFallback ?? this.isServerFallback,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  factory Message.fromMap(Map<String, dynamic> map) {
    final text = (map['text'] ?? '') as String;

    // Handle both the legacy 'photoPath' (single string) and
    // the new 'attachmentPaths' (list/json) structures.
    final List<String> paths = [];

    // 1. Check for new list format (in-memory usage)
    if (map['attachmentPaths'] != null) {
      if (map['attachmentPaths'] is List) {
        paths.addAll((map['attachmentPaths'] as List).cast<String>());
      }
    }
    // 2. Parse the 'photoPath' column from database
    // It can be: (a) JSON array string like '["path1", "path2"]'
    //            (b) Legacy single path string
    else if (map['photoPath'] != null &&
        map['photoPath'] is String &&
        (map['photoPath'] as String).isNotEmpty) {
      final photoPathValue = map['photoPath'] as String;

      // Check if it's a JSON array
      if (photoPathValue.trim().startsWith('[')) {
        try {
          final List<dynamic> decoded = jsonDecode(photoPathValue);
          paths.addAll(decoded.cast<String>());
        } catch (e) {
          // Fallback: treat as legacy single path if JSON decode fails
          paths.add(photoPathValue);
        }
      } else {
        // Legacy single path
        paths.add(photoPathValue);
      }
    }

    List<dynamic>? webSearchSources;
    if (map['webSearchSources'] != null) {
      if (map['webSearchSources'] is String) {
        try {
          webSearchSources = jsonDecode(map['webSearchSources'] as String);
        } catch (e) {
          // Handle error if JSON decoding fails
          webSearchSources = null;
        }
      } else if (map['webSearchSources'] is List) {
        webSearchSources = map['webSearchSources'] as List<dynamic>;
      }
    }

    return Message._private(
      id: map['uuid'] as String?,
      text: text,
      isUserMessage: (map['isUser'] as int? ?? 0) == 1,
      attachmentPaths: paths,
      model: map['model'] as String?,
      includeInContext: (map['includeInContext'] as int? ?? 1) == 1,
      isReported: (map['isReported'] as int? ?? 0) == 1,
      isThinking: (map['isThinking'] as int? ?? 0) == 1,
      isError: (map['isError'] as int? ?? 0) == 1,
      opacity: 1.0,
      isAttachmentUploading: false,
      parsedSpans: null,
      notifier: ValueNotifier(text),
      isVisible: (map['isVisible'] as int? ?? 1) == 1,
      isWebSearchActive: (map['isWebSearchActive'] as int? ?? 0) == 1,
      webSearchSources: webSearchSources,
      pendingMediaType: MediaGenerationType.none,
      isServerFallback: (map['isServerFallback'] as int? ?? 0) == 1,
    timestamp: map['ts'] != null ? DateTime.fromMillisecondsSinceEpoch(map['ts'] as int) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'uuid': id,
      'text': text,
      'isUser': isUserMessage ? 1 : 0,
      'attachmentPaths': attachmentPaths,
      'model': model,
      'includeInContext': includeInContext ? 1 : 0,
      'isReported': isReported ? 1 : 0,
      'isThinking': isThinking ? 1 : 0,
      'isError': isError ? 1 : 0,
      'opacity': opacity,
      'isAttachmentUploading': isAttachmentUploading ? 1 : 0,
      'isVisible': isVisible ? 1 : 0,
      'isWebSearchActive': isWebSearchActive ? 1 : 0,
      'webSearchSources': webSearchSources != null ? jsonEncode(
          webSearchSources) : null,
      'isServerFallback': isServerFallback ? 1 : 0,
      'ts': timestamp?.millisecondsSinceEpoch,
    };
  }
}
